apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: choz3gijg-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:cabd0ed3d45a23f4c4bf59e55a86cc7bc02c4d45@sha256:95040fa9603c20228bc3b302affa46ed24aaf2a908f5a0d666bf25ddaed96ce8
          name: container-image
